const { Questions } = require('../models');

const questionsData = [
  {
    question: "You've made it to Hogwarts, which means you've already brought a wand from Ollivander's, What material is at its core? ",
    choices1: "Phoenix Feather",
    choices2: "Dragon Heartstring",
    choices3: "Unicorn Hair",
    choices4: "Arachnid Fang",
    quiz_id: 1,
  },
  {
    question: "Choose a Deathly Hallow",
    choices1: "The Elder Wand",
    choices2: "The Resurrection Stone",
    choices3: "The Cloak of Invisibility",
    choices4: "None",
    quiz_id: 1,
  },
  {
    question: "Which path do you intend to follow after leaving Hogwarts?",
    choices1: "I'd join the Ministry - I want to make a difference in the world",
    choices2: "I think I'd travel for a while before committing to a carrer.",
    choices3: "I'd settle down and start a family as soon as possible!",
    choices4: "I'd continue to work hard in order to achieve as much success as possible.",
    quiz_id: 1,
  },
  {
    question: "What would you see in the Mirror of Erised?",
    choices1: "Myself, surrounded by riches",
    choices2: "Myself, surrounded by loving family and friends",
    choices3: "Myself, knowledgable above all",
    choices4: "Myself, experiencing a marvellous adventure",
    quiz_id: 1,
  },
  {
    question: "It's Saturday, you've finished your homework, and you have some free time. You decide to spend some time away from you common room. Where do you go?",
    choices1: "The Forbidden Forest",
    choices2: "The library",
    choices3: "The kitchens",
    choices4: "The Room of Requirements",
    quiz_id: 1,
  },
  {
    question: "You're allowed a pet at Hogwarts, an owl, a cat, or a toad. Which do you bring?",
    choices1: "Owl",
    choices2: "Cat",
    choices3: "Toad",
    choices4: "Nothing, I cant be trusted to look after a pet!",
    quiz_id: 1,
  },
  {
    question: "The first Quidditch match of the season is approaching, and you can't wait to get involved. What role are you playing?",
    choices1: "Seeker. Iwant the glory!",
    choices2: "Chaser. I like to be involved, and work as part of the team",
    choices3: "Beater. I like having all that power",
    choices4: "Ill be in the crowd, making sure supporter morale is high!",
    quiz_id: 1,
  },
  {
    question: "Which of your skills are you most proud of?",
    choices1: "My ability to absorb new information",
    choices2: "My ability to make new friends",
    choices3: "My ability to get what I want",
    choices4: "My ability to keep secrets",
    quiz_id: 1,
  },
  {
    question: "Which of the following would you most like to study?",
    choices1: "Werewolves",
    choices2: "Ghosts",
    choices3: "Goblins",
    choices4: "Centaurs",
    quiz_id: 1,
  },
  {
    question: "Given the choice, would you rather invent a potion that would gurantee you",
    choices1: "Glory",
    choices2: "Love",
    choices3: "Power",
    choices4: "Wisdom",
    quiz_id: 1,
  },
  {
    question: "Once every century, the Flutterby bush produces flowers that adapt their scent to attract",
    choices1: "The sea",
    choices2: "Home",
    choices3: "A crackling log fire",
    choices4: "Fresh parchment",
    quiz_id: 1,
  },
  {
    question: "Which quality do you value most?",
    choices1: "Intelligence",
    choices2: "Ambition",
    choices3: "Patience",
    choices4: "Courage",
    quiz_id: 1,
  },
  {
    question: "What is your favorite color?",
    choices1: "Red",
    choices2: "Yellow",
    choices3: "Blue",
    choices4: "Green",
    quiz_id: 1,
  },
  {
    question: "What spell would you cast",
    choices1: "Crucio",
    choices2: "Riddikulus",
    choices3: "Protego",
    choices4: "Absorbos librus",
    quiz_id: 1,
  },
  {
    question: "What is your patronus",
    choices1: "Stag",
    choices2: "Otter",
    choices3: "Phoneix",
    choices4: "Snake",
    quiz_id: 1,
  },

];

const seedQuestions = () => Questions.bulkCreate(questionsData);

module.exports = seedQuestions;